apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cinema-app
  description: Front DevOps – aplicación de ejemplo
  annotations:
    github.com/project-slug: Harol000379440f/cinema-app
spec:
  type: service
  lifecycle: experimental
  owner: user:default/harolrueda
