name: Build, Scan, and Push Docker Image # Nombre del workflow

on:
  push:
    branches:
      - main # Este pipeline se ejecutará cuando se haga push a la rama "main"

jobs:
  build-and-scan-and-push:
    runs-on: ubuntu-latest # Utiliza el último sistema Ubuntu como entorno de ejecución
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          echo "Starting Docker build..."
          DOCKER_USERNAME=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          echo "Using Docker username: $DOCKER_USERNAME"
          docker build -t $DOCKER_USERNAME/cinema-app:latest .
          echo "Docker build completed."
          echo "Listing Docker images..."
          docker images
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/cinema-app:latest
          severity: CRITICAL,HIGH,MEDIUM
          ignore-unfixed: true
          exit-code: 1
      - name: Push Docker Image
        if: success()
        run: |
          echo "Starting Docker push..."
          DOCKER_USERNAME=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          docker push $DOCKER_USERNAME/cinema-app:latest
          echo "Docker push completed."
      - name: Unit Test Docker Workflow
        if: success()
        run: |
          echo "Running pipeline tests..."
          DOCKER_USERNAME=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          if [ -z "$DOCKER_USERNAME" ]; then
            echo "Error: DOCKER_USERNAME is empty"
            exit 1
          fi
          if [ "$DOCKER_USERNAME" != "$(echo "$DOCKER_USERNAME" | tr '[:upper:]' '[:lower:]')" ]; then
            echo "Error: DOCKER_USERNAME is not lowercase"
            exit 1
          fi
          echo "DOCKER_USERNAME validation passed"
          echo "Validating Docker image build..."
          docker inspect --type=image "$DOCKER_USERNAME/cinema-app:latest" > /dev/null 2>&1
          if [ $? -ne 0 ]; then
            echo "Error: Docker image $DOCKER_USERNAME/cinema-app:latest not found"
            exit 1
          fi
          echo "Docker image build validation passed"
          echo "Validating Docker push (mock test)..."
          MOCK_PUSH_RESULT=0
          if [ $MOCK_PUSH_RESULT -ne 0 ]; then
            echo "Error: Docker image push failed"
            exit 1
          fi
          echo "Docker push validation passed"
          echo "All pipeline tests passed successfully."