name: Build and Push Docker Image #Nma workflow

on: #Evento
  push:
    branches:
      - main

jobs: 
  build-and-push: #Name Runner 
    runs-on: ubuntu-latest
    steps:      #Step inicial
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Docker Image
        run: | 
          echo "Secrets ${{ secrets.DOCKER_USERNAME }} "
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:latest