name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-scan-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          DOCKER_USERNAME=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          docker build -t $DOCKER_USERNAME/cinema-app:latest .
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/cinema-app:latest
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          format: json
          output: trivy-report.json
        continue-on-error: true
      - name: Push Docker Image
        if: steps.trivy.outputs.exit-code == 0
        run: |
          DOCKER_USERNAME=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          docker push $DOCKER_USERNAME/cinema-app:latest
      - name: Send Notification
        if: steps.trivy.outputs.exit-code != 0
        uses: actions/notify@v3
        with:
          if: always
          channels: your-notification-channel
          message: "Se encontraron vulnerabilidades en la imagen Docker. Revisa el reporte de Trivy (trivy-report.json)."